services:
  - type: web
    name: mon-backend-university
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn django_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
      - key: PYTHON_VERSION
        value: 3.11
