# services:
#   - type: web
#     name: my-backend-app
#     env: python
#     branch: main
#     buildCommand: "pip install -r requirements.txt"
#     startCommand: "gunicorn django_project.wsgi:application"
#     envVars:
#       - key: DJANGO_SETTINGS_MODULE
#         value: django_project.settings
#       - key: PYTHON_VERSION
#         value: 3.11
#       - key: SECRET_KEY
#         value: "b+&9d!ac_ld$+1qc7p^=5yue)crwylftaxqf8)oc_4xvw=_#a4"
